version: '3'
services:
  local-db:
    image: library/mysql:5.7
    container_name: mlops
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: mlops
      TZ: Asia/Seoul
    volumes:
      - ./db/mysql/data:/var/lib/mysql
      - ./db/mysql/init:/docker-entrypoint-initdb.d
    platform: linux/x86_64
    command: # utf8로 인코딩해주는 명령어들
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
